apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: jvb
  name: jvb
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: jvb
    spec:
      containers:
      - env:
        - name: XMPP_SERVER
          value: prosody
        - name: DOCKER_HOST_ADDRESS
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: XMPP_DOMAIN
          value: {{ .Values.xmpp.domain }}
        - name: XMPP_AUTH_DOMAIN
          value: {{ .Values.xmpp.auth.domain }}
        - name: JVB_PORT
          value: {{ .Values.jvb.port.udp | quote }}
        - name: JVB_TCP_PORT
          value: {{ .Values.jvb.port.tcp | quote }}
        - name: JVB_AUTH_USER
          value: {{ .Values.jvb.auth.user }}
        - name: JVB_AUTH_PASSWORD
          value: {{ .Values.jvb.auth.password }}
        - name: JVB_BREWERY_MUC
          value: {{ .Values.jvb.muc }}
        - name: XMPP_INTERNAL_MUC_DOMAIN
          value: {{ .Values.xmpp.domain.internal }}
        - name: JVB_STUN_SERVERS
          value: {{ .Values.jvb.stunServers }}
        - name: JICOFO_AUTH_USER
          value: {{ .Values.jicofo.auth.user }}
        - name: TZ
          value: {{ .Values.TZ }}
        image: {{ .Values.jvb.image }}
        name: jvb
        ports:
        - containerPort: {{ .Values.jvb.port.udp }}
          protocol: UDP
        - containerPort: {{ .Values.jvb.port.tcp }}
        resources: {}
      restartPolicy: Always
status: {}
