apiVersion: v1
kind: Service
metadata:
  labels:
    app: jitsi
  name: jvb
spec:
  type: LoadBalancer
  ports:
  - name: JVB_UDP
    port: {{ .Values.jvb.port.udp }}
    protocol: UDP
    targetPort: {{ .Values.jvb.port.udp }}
  - name: JVB_TCP
    port: {{ .Values.jvb.port.tcp }}
    protocol: TCP
    targetPort: {{ .Values.jvb.port.tcp}}
  selector:
    service: jvb
