apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ template "jitsi.namespace" . }}
  name: jvb
  labels:
    service: jvb
spec:
  replicas: 1
  selector:
    matchLabels:
      service: jvb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: jvb
    spec:
      containers:
      - name: jvb
        image: {{ .Values.jvb.image }}
        env:
          - name: XMPP_SERVER
            value: prosody
          - name: DOCKER_HOST_ADDRESS
            value: {{ .Values.jvb.loadBalancerIP }}
          - name: XMPP_DOMAIN
            value: {{ .Values.xmpp.domain }}
          - name: XMPP_AUTH_DOMAIN
            value: {{ .Values.xmpp.auth.domain }}
          - name: JVB_PORT
            value: {{ .Values.jvb.port.udp | quote }}
          - name: JVB_TCP_PORT
            value: {{ .Values.jvb.port.tcp | quote }}
          - name: JVB_COMPONENT_SECRET
            valueFrom:
              secretKeyRef:
                name: {{ .Values.jvb.existingSecret | default (include "jitsi.jvb.secret" .) }}
                key: component-secret
          - name: JVB_AUTH_USER
            value: {{ .Values.jvb.auth.user }}
          - name: JVB_AUTH_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.jvb.existingSecret | default (include "jitsi.jvb.secret" .) }}
                key: auth-password
          - name: JVB_BREWERY_MUC
            value: {{ .Values.jvb.muc }}
          - name: XMPP_INTERNAL_MUC_DOMAIN
            value: {{ .Values.xmpp.muc.internal }}
          - name: JVB_STUN_SERVERS
            value: {{ .Values.jvb.stunServers }}
          - name: JICOFO_AUTH_USER
            value: {{ .Values.jicofo.auth.user }}
          - name: TZ
            value: {{ .Values.TZ }}
        ports:
        - containerPort: {{ .Values.jvb.port.udp }}
          protocol: UDP
        - containerPort: {{ .Values.jvb.port.tcp }}
        resources: {}
      restartPolicy: Always
status: {}
