apiVersion: v1
kind: Service
metadata:
  namespace: {{ template "jitsi.namespace" . }}
  name: web
  labels:
    service: web
spec:
  ports:
  - name: "http"
    port: 80
    targetPort: 80
  - name: "https"
    port: 443
    targetPort: 443
  selector:
    service: web
